# Generated by Django 4.2.9 on 2024-01-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ThongTin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maVCNLD', models.CharField(max_length=10)),
                ('maCanBo', models.CharField(max_length=10)),
                ('hoTen', models.CharField(max_length=100)),
                ('ngaySinh', models.DateField()),
                ('gioiTinh', models.BooleanField(blank=True)),
                ('queQuan', models.CharField(blank=True, max_length=100, null=True)),
                ('soDienThoai', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('thoiGianBatDauCT', models.DateField(blank=True, null=True)),
                ('trangThai', models.BooleanField(blank=True)),
                ('isLanhDao', models.BooleanField(blank=True)),
                ('isKiemNhiemNoiKhac', models.BooleanField(blank=True)),
                ('isGiangVien', models.BooleanField(blank=True)),
                ('isNghienCuuVien', models.BooleanField(blank=True)),
                ('hinhThucGiaoKet', models.CharField(blank=True, max_length=100, null=True)),
                ('doiTuongCanBo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThongTin.doituongcanbo')),
                ('donVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThongTin.donvi')),
            ],
        ),
    ]
